services:
  - type: web
    name: profees-backend
    env: docker
    region: singapore
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: SERVER_PORT
        value: 8080
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: profees-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: profees-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: profees-db
          property: password
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: profees-db
    region: singapore
    plan: free
    databaseName: adminITI
    ipAllowList: []
