services:
  - type: web
    name: profees-backend
    env: docker
    region: singapore
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: SERVER_PORT
        value: 8080
      - key: DATABASE_URL
        fromDatabase:
          name: profees-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: profees-db
    region: singapore
    plan: free
    databaseName: adminiti
    ipAllowList: []
